language: python
sudo: false
python:
- 3.5.1

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pip-accel

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install pip-accel
  
  - pip-accel install -r requirements/development.txt

before_script:
- export DATABASE_URL=postgres://postgres@localhost/steelrumors
- psql -c "CREATE DATABASE steelrumors;" -U postgres

script:
- flake8
- py.test --cov -v --tb=native


notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]

deploy:
  provider: heroku
  buildpack: python
  strategy: api
  api_key:
    # travis encrypt $(heroku auth:token) --add deploy.api_key
    secure: <add_heroku_auth_token_here>
  app:
    master: steelrumors-dev
    qa: steelrumors-qa
    prod: steelrumors-prod
  on:
    repo: mmadil/steelrumors-web
